// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBG2YSYHo5F3bMAI9saVQBk5Os4jnxI7g0',
    appId: '1:812543613939:web:349d673b26c85867c85086',
    messagingSenderId: '812543613939',
    projectId: 'creative-26ef3',
    authDomain: 'creative-26ef3.firebaseapp.com',
    storageBucket: 'creative-26ef3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzs0-nPngcuJIXY-e9eqM-xl3gRA-Evs0',
    appId: '1:812543613939:android:f966db1bbb6c3da9c85086',
    messagingSenderId: '812543613939',
    projectId: 'creative-26ef3',
    storageBucket: 'creative-26ef3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkhooz3hFyoJHR7lEDV3L0zAKenR78-eA',
    appId: '1:812543613939:ios:b60dc1b36f5ebfc5c85086',
    messagingSenderId: '812543613939',
    projectId: 'creative-26ef3',
    storageBucket: 'creative-26ef3.appspot.com',
    iosClientId: '812543613939-394ck8njnsq6gdd4fs445bmahge2cudh.apps.googleusercontent.com',
    iosBundleId: 'com.example.green',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkhooz3hFyoJHR7lEDV3L0zAKenR78-eA',
    appId: '1:812543613939:ios:b60dc1b36f5ebfc5c85086',
    messagingSenderId: '812543613939',
    projectId: 'creative-26ef3',
    storageBucket: 'creative-26ef3.appspot.com',
    iosClientId: '812543613939-394ck8njnsq6gdd4fs445bmahge2cudh.apps.googleusercontent.com',
    iosBundleId: 'com.example.green',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBG2YSYHo5F3bMAI9saVQBk5Os4jnxI7g0',
    appId: '1:812543613939:web:2c01530d0e0165ebc85086',
    messagingSenderId: '812543613939',
    projectId: 'creative-26ef3',
    authDomain: 'creative-26ef3.firebaseapp.com',
    storageBucket: 'creative-26ef3.appspot.com',
  );
}
